Repository prgrms-web-devcourse-final-project/WEB5_6_DOD_BE, pull requests merged in 2025-07, with the labels that each got.

#1 chore : prod, local.yml 파일 gitignore에 추가
  .gitignore
Labels: ✅ done, 📝 documentation

#4 🐛 fix: 삭제된 MiddleRegion 이 임포트 되어 실행이 되지 않던 문제 해결
  src/main/java/com/grepp/spring/app/controller/api/schedules/payload/ShowSuggestedLocationsResponse.java
  src/main/java/com/grepp/spring/app/model/location/domain/Location.java
Labels: 🐛bug

#21 🐛 fix: GroupMember 엔티티 수정
  src/main/java/com/grepp/spring/app/model/group/dto/GroupMemberCreateDto.java
  src/main/java/com/grepp/spring/app/model/group/entity/GroupMember.java
  src/main/java/com/grepp/spring/app/model/group/service/GroupService.java
Labels: 🐛bug

#24 ✨ feat: OAuth2 소셜 로그인 기능 구현 완료
  src/main/java/com/grepp/spring/app/controller/api/auth/AuthController.java
  src/main/java/com/grepp/spring/app/model/auth/AuthService.java
  src/main/java/com/grepp/spring/app/model/member/entity/Member.java
  src/main/java/com/grepp/spring/infra/auth/jwt/TokenCookieFactory.java
  src/main/java/com/grepp/spring/infra/auth/oauth2/OAuth2FailureHandler.java
  src/main/java/com/grepp/spring/infra/auth/oauth2/OAuth2SuccessHandler.java
  src/main/java/com/grepp/spring/infra/auth/oauth2/user/GoogleOAuth2UserInfo.java
  src/main/java/com/grepp/spring/infra/auth/oauth2/user/GreppOAuth2UserInfo.java
  src/main/java/com/grepp/spring/infra/auth/oauth2/user/KakaoOAuth2UserInfo.java
  src/main/java/com/grepp/spring/infra/auth/oauth2/user/OAuth2UserInfo.java
  src/main/java/com/grepp/spring/infra/config/WebConfig.java
  src/main/java/com/grepp/spring/infra/config/security/SecurityConfig.java
Labels: ✨ feature

#31 ✨ feat: 사용자 정보 조회 및 로그아웃 기능 구현
  src/main/java/com/grepp/spring/app/controller/api/auth/AuthController.java
  src/main/java/com/grepp/spring/app/controller/api/member/MemberController.java
  src/main/java/com/grepp/spring/app/controller/api/member/payload/MemberInfoResponse.java
  src/main/java/com/grepp/spring/app/model/member/repository/MemberRepository.java
  src/main/java/com/grepp/spring/app/model/member/service/MemberService.java
Labels: ✅ done, ✨ feature

#32 ✨ feat: 일정 - 일정 생성 기능 구현
  src/main/java/com/grepp/spring/app/controller/api/schedules/ScheduleController.java
  src/main/java/com/grepp/spring/app/controller/api/schedules/payload/request/CreateSchedulesRequest.java
  src/main/java/com/grepp/spring/app/model/schedule/dto/CreateScheduleDto.java
  src/main/java/com/grepp/spring/app/model/schedule/dto/ScheduleMemberRolesDto.java
  src/main/java/com/grepp/spring/app/model/schedule/entity/Schedule.java
  src/main/java/com/grepp/spring/app/model/schedule/entity/ScheduleMember.java
  src/main/java/com/grepp/spring/app/model/schedule/repository/LocationCommandRepository.java
  src/main/java/com/grepp/spring/app/model/schedule/repository/LocationQueryRepository.java
  src/main/java/com/grepp/spring/app/model/schedule/repository/ScheduleCommandRepository.java
  src/main/java/com/grepp/spring/app/model/schedule/repository/ScheduleMemberCommandRepository.java
  src/main/java/com/grepp/spring/app/model/schedule/repository/ScheduleMemberQueryRepository.java
  src/main/java/com/grepp/spring/app/model/schedule/repository/ScheduleQueryRepository.java
  src/main/java/com/grepp/spring/app/model/schedule/repository/VoteCommandRepository.java
  src/main/java/com/grepp/spring/app/model/schedule/repository/VoteQueryRepository.java
  src/main/java/com/grepp/spring/app/model/schedule/repository/WorkspaceCommandRepository.java
  src/main/java/com/grepp/spring/app/model/schedule/repository/WorkspaceQueryRepository.java
  src/main/java/com/grepp/spring/app/model/schedule/service/ScheduleCommandService.java
  src/main/java/com/grepp/spring/app/model/schedule/service/ScheduleQueryService.java
Labels: ✨ feature

#33 ✨ feat: 일정 - 일정 삭제 기능 구현
  src/main/java/com/grepp/spring/app/controller/api/schedules/ScheduleController.java
  src/main/java/com/grepp/spring/app/model/schedule/repository/ScheduleCommandRepository.java
  src/main/java/com/grepp/spring/app/model/schedule/repository/ScheduleMemberCommandRepository.java
  src/main/java/com/grepp/spring/app/model/schedule/repository/ScheduleMemberQueryRepository.java
  src/main/java/com/grepp/spring/app/model/schedule/service/ScheduleCommandService.java
  src/main/resources/lkh.sql
Labels: ✨ feature

#35 ✨ feat: 이벤트 개인 시간대 입력/수정 기능 구현
  src/main/java/com/grepp/spring/app/controller/api/event/EventController.java
  src/main/java/com/grepp/spring/app/controller/api/event/payload/request/MyTimeScheduleRequest.java
  src/main/java/com/grepp/spring/app/model/event/dto/MyTimeScheduleDto.java
  src/main/java/com/grepp/spring/app/model/event/entity/TempSchedule.java
  src/main/java/com/grepp/spring/app/model/event/repository/EventMemberRepository.java
  src/main/java/com/grepp/spring/app/model/event/repository/TempScheduleRepository.java
  src/main/java/com/grepp/spring/app/model/event/service/EventService.java
Labels: ✨ feature

#37 ✨ feat: 즐겨찾기 장소 및 시간대 조회 + 시간대 중복 등록 방지
  src/main/java/com/grepp/spring/app/controller/api/mypage/MypageController.java
  src/main/java/com/grepp/spring/app/controller/api/mypage/payload/request/CreateFavoritePlaceRequest.java
  src/main/java/com/grepp/spring/app/controller/api/mypage/payload/request/CreateFavoriteTimeRequest.java
  src/main/java/com/grepp/spring/app/model/mypage/repository/MyLocationRepository.java
  src/main/java/com/grepp/spring/app/model/mypage/repository/MyTimetableRepository.java
  src/main/java/com/grepp/spring/app/model/mypage/service/MypageService.java
Labels: ✨ feature, 🔧 enhancement

#45 ✨ feat: 참여자 전원의 가능한 시간대 조회 기능 구현
  src/main/java/com/grepp/spring/app/controller/api/event/EventController.java
  src/main/java/com/grepp/spring/app/controller/api/event/payload/response/AllTimeScheduleResponse.java
  src/main/java/com/grepp/spring/app/model/event/dto/AllTimeScheduleDto.java
  src/main/java/com/grepp/spring/app/model/event/entity/EventMember.java
  src/main/java/com/grepp/spring/app/model/event/repository/CandidateDateRepository.java
  src/main/java/com/grepp/spring/app/model/event/repository/EventMemberRepository.java
  src/main/java/com/grepp/spring/app/model/event/repository/TempScheduleRepository.java
  src/main/java/com/grepp/spring/app/model/event/service/EventService.java
Labels: ✨ feature

#50 ✨ feat: 즐겨찾기 장소 수정 & 즐겨찾기 시간대 등록 + 수정 통합 기능 구현
  src/main/java/com/grepp/spring/app/controller/api/mypage/MypageController.java
  src/main/java/com/grepp/spring/app/controller/api/mypage/payload/request/CreateFavoritePlaceRequest.java
  src/main/java/com/grepp/spring/app/controller/api/mypage/payload/request/CreateFavoriteTimeRequest.java
  src/main/java/com/grepp/spring/app/controller/api/mypage/payload/request/ModifyFavoritePlaceRequest.java
  src/main/java/com/grepp/spring/app/controller/api/mypage/payload/request/ModifyFavoriteTimeRequest.java
  src/main/java/com/grepp/spring/app/controller/api/mypage/payload/request/ShowFavoritePlaceRequest.java
  src/main/java/com/grepp/spring/app/controller/api/mypage/payload/request/ShowFavoriteTimeRequest.java
  src/main/java/com/grepp/spring/app/controller/api/mypage/payload/response/CreateFavoriteTimeResponse.java
  src/main/java/com/grepp/spring/app/controller/api/mypage/payload/response/ModifyFavoritePlaceResponse.java
  src/main/java/com/grepp/spring/app/controller/api/mypage/payload/response/ShowFavoriteTimeResponse.java
  src/main/java/com/grepp/spring/app/model/mypage/dto/FavoriteLocationDto.java
  src/main/java/com/grepp/spring/app/model/mypage/dto/FavoriteTimetableDto.java
  src/main/java/com/grepp/spring/app/model/mypage/entity/FavoriteTimetable.java
  src/main/java/com/grepp/spring/app/model/mypage/repository/MyTimetableRepository.java
  src/main/java/com/grepp/spring/app/model/mypage/service/MypageService.java
Labels: ♻️ refactor, ✨ feature

#59 ✨ feat: group 멤버 조회 + groupService에서의 예외들을 전역핸들러로 응답
  src/main/java/com/grepp/spring/app/controller/api/group/GroupController.java
  src/main/java/com/grepp/spring/app/controller/api/group/payload/response/ShowGroupMemberResponse.java
  src/main/java/com/grepp/spring/app/model/group/repository/GroupMemberQueryRepository.java
  src/main/java/com/grepp/spring/app/model/group/service/GroupQueryService.java
  src/main/java/com/grepp/spring/infra/error/exceptions/group/GroupNotFoundException.java
  src/main/java/com/grepp/spring/infra/error/exceptions/group/NotGroupUserException.java
  src/main/java/com/grepp/spring/infra/error/groupAdvice/GroupExceptionAdvice.java
  src/main/java/com/grepp/spring/infra/response/ApiResponse.java
  src/main/java/com/grepp/spring/infra/response/GroupErrorCode.java
Labels: ✨ feature, 🔥 매운맛

#72 ✨ feat: 온라인 플랫폼 생성 api 구현 (실제 플랫폼 생성 x)
  src/main/java/com/grepp/spring/app/controller/api/schedules/ScheduleController.java
  src/main/java/com/grepp/spring/app/controller/api/schedules/payload/response/CreateOnlineMeetingRoomResponse.java
  src/main/java/com/grepp/spring/app/model/schedule/dto/AddWorkspaceDto.java
  src/main/java/com/grepp/spring/app/model/schedule/dto/CreateOnlineMeetingRoomDto.java
  src/main/java/com/grepp/spring/app/model/schedule/entity/Schedule.java
  src/main/java/com/grepp/spring/app/model/schedule/service/ScheduleCommandService.java
  src/main/java/com/grepp/spring/app/model/schedule/service/ScheduleQueryService.java
  src/main/resources/lkh.sql
Labels: ✨ feature

#73 ✨ feat 그룹 정보 수정
  src/main/java/com/grepp/spring/app/controller/api/group/GroupController.java
  src/main/java/com/grepp/spring/app/controller/api/group/payload/request/ModifyGroupInfoRequest.java
  src/main/java/com/grepp/spring/app/model/group/service/GroupCommandModifyGroupService.java
Labels: ✨ feature, 💧 순한맛

#82 ♻️ refactor: 엔티티 클래스 Cascade 옵션 추가
  src/main/java/com/grepp/spring/app/model/event/entity/Event.java
  src/main/java/com/grepp/spring/app/model/event/entity/EventMember.java
  src/main/java/com/grepp/spring/app/model/group/entity/Group.java
  src/main/java/com/grepp/spring/app/model/mainpage/entity/Calendar.java
  src/main/java/com/grepp/spring/app/model/member/entity/Member.java
  src/main/java/com/grepp/spring/app/model/schedule/entity/Location.java
  src/main/java/com/grepp/spring/app/model/schedule/entity/Schedule.java
  src/main/java/com/grepp/spring/app/model/schedule/entity/ScheduleMember.java
Labels: ♻️ refactor, 💧 순한맛, 🔧 enhancement

#95 그룹 탈퇴 기능 구현
  src/main/java/com/grepp/spring/app/controller/api/group/GroupController.java
  src/main/java/com/grepp/spring/app/model/event/repository/EventMemberRepository.java
  src/main/java/com/grepp/spring/app/model/event/repository/EventRepository.java
  src/main/java/com/grepp/spring/app/model/group/repository/GroupMemberCommandRepository.java
  src/main/java/com/grepp/spring/app/model/group/repository/GroupMemberQueryRepository.java
  src/main/java/com/grepp/spring/app/model/group/service/GroupCommandWithdrawService.java
  src/main/java/com/grepp/spring/app/model/schedule/repository/ScheduleMemberCommandRepository.java
  src/main/java/com/grepp/spring/app/model/schedule/repository/ScheduleMemberQueryRepository.java
  src/main/java/com/grepp/spring/app/model/schedule/repository/ScheduleQueryRepository.java
  src/main/java/com/grepp/spring/infra/error/exceptions/group/OnlyOneGroupLeaderException.java
  src/main/java/com/grepp/spring/infra/error/groupAdvice/GroupExceptionAdvice.java
  src/main/java/com/grepp/spring/infra/response/GroupErrorCode.java
Labels: ✨ feature, 🔥 매운맛

#97 ♻️ refactor: 일정 조회 response meetingType 추가
  src/main/java/com/grepp/spring/app/controller/api/schedules/ScheduleController.java
  src/main/java/com/grepp/spring/app/controller/api/schedules/payload/response/ShowScheduleResponse.java
  src/main/java/com/grepp/spring/app/model/schedule/dto/ShowScheduleDto.java
  src/main/java/com/grepp/spring/app/model/schedule/entity/Line.java
  src/main/java/com/grepp/spring/app/model/schedule/service/ScheduleCommandService.java
  src/main/java/com/grepp/spring/app/model/schedule/service/ScheduleQueryService.java
  src/main/java/com/grepp/spring/infra/config/security/SecurityConfig.java
Labels: ✨ feature, 🔧 enhancement

#98 ✨ feat: 메인페이지 - 그룹 및 일정&캘린더 조회 기능
  src/main/java/com/grepp/spring/app/controller/api/mainpage/CalendarController.java
  src/main/java/com/grepp/spring/app/controller/api/mainpage/MainPageController.java
  src/main/java/com/grepp/spring/app/controller/api/mainpage/payload/response/CombinedCalendarResponse.java
  src/main/java/com/grepp/spring/app/controller/api/mainpage/payload/response/ShowMainPageResponse.java
  src/main/java/com/grepp/spring/app/controller/api/mypage/CalendarOAuthController.java
  src/main/java/com/grepp/spring/app/controller/api/mypage/MypageController.java
  src/main/java/com/grepp/spring/app/controller/api/mypage/payload/request/CreateFavoriteTimeRequest.java
  src/main/java/com/grepp/spring/app/controller/api/mypage/payload/response/ModifyFavoriteTimeResponse.java
  src/main/java/com/grepp/spring/app/controller/api/mypage/payload/response/MypageInfoResponse.java
  src/main/java/com/grepp/spring/app/model/auth/AuthService.java
  src/main/java/com/grepp/spring/app/model/mainpage/code/ScheduleSource.java
  src/main/java/com/grepp/spring/app/model/mainpage/dto/EmptyDto.java
  src/main/java/com/grepp/spring/app/model/mainpage/dto/UnifiedScheduleDto.java
  src/main/java/com/grepp/spring/app/model/mainpage/entity/Calendar.java
  src/main/java/com/grepp/spring/app/model/mainpage/entity/CalendarDetail.java
  src/main/java/com/grepp/spring/app/model/mainpage/repository/EmptyRepository.java
  src/main/java/com/grepp/spring/app/model/mainpage/repository/GoogleScheduleRepository.java
  src/main/java/com/grepp/spring/app/model/mainpage/repository/MainPageScheduleRepository.java
  src/main/java/com/grepp/spring/app/model/mainpage/service/CalendarService.java
  src/main/java/com/grepp/spring/app/model/mainpage/service/GoogleScheduleService.java
  src/main/java/com/grepp/spring/app/model/mainpage/service/MainPageScheduleService.java
  src/main/java/com/grepp/spring/app/model/mainpage/service/MainPageService.java
  src/main/java/com/grepp/spring/app/model/member/repository/SocialAuthTokenRepository.java
  src/main/java/com/grepp/spring/app/model/mypage/dto/GoogleEventDto.java
  src/main/java/com/grepp/spring/app/model/mypage/service/CalendarSyncService.java
  src/main/java/com/grepp/spring/app/model/mypage/service/GoogleOAuthService.java
  src/main/java/com/grepp/spring/app/model/mypage/service/SocialAuthTokenService.java
  src/main/resources/jsy.sql
Labels: ♻️ refactor, ✅ done, ✨ feature

#100 ✨ feat 그룹 멤버 추가(링크를 통해 들어온 멤버)
  src/main/java/com/grepp/spring/app/controller/api/group/GroupController.java
  src/main/java/com/grepp/spring/app/controller/api/group/payload/response/CreateGroupResponse.java
  src/main/java/com/grepp/spring/app/controller/api/group/payload/response/InviteGroupMemberResponse.java
  src/main/java/com/grepp/spring/app/controller/api/group/payload/response/ModifyGroupInfoResponse.java
  src/main/java/com/grepp/spring/app/model/group/repository/GroupMemberQueryRepository.java
  src/main/java/com/grepp/spring/app/model/group/service/GroupCommandModifyGroupService.java
  src/main/java/com/grepp/spring/app/model/group/service/GroupCommandService.java
Labels: ✨ feature, 💧 순한맛

#107 ✨ feat 그룹 내 일정 조회
  src/main/java/com/grepp/spring/app/controller/api/group/GroupController.java
  src/main/java/com/grepp/spring/app/controller/api/group/payload/response/ShowGroupScheduleResponse.java
  src/main/java/com/grepp/spring/app/model/group/dto/ScheduleDetails.java
  src/main/java/com/grepp/spring/app/model/group/service/GroupQueryGroupScheduleService.java
Labels: ✨ feature

#111 ✨ feat 일회성 일정들이 편입할 수 있는 그룹 조회
  src/main/java/com/grepp/spring/app/controller/api/group/GroupController.java
  src/main/java/com/grepp/spring/app/controller/api/group/payload/response/ShowCandidateGroupResponse.java
  src/main/java/com/grepp/spring/app/model/group/dto/GroupCandidateDto.java
  src/main/java/com/grepp/spring/app/model/group/service/GroupQueryGroupTransferCandidateService.java
Labels: ✨ feature, 🔥 매운맛

#112 ✨ feat 일회성 일정을 그룹에 편입 기능 구현
  src/main/java/com/grepp/spring/app/controller/api/group/GroupController.java
  src/main/java/com/grepp/spring/app/model/group/service/GroupCommandGroupTransferService.java
Labels: ✨ feature, 🔥 매운맛

#120 ✨ feat: 전체 시간대 조회 응답값 추가
  src/main/java/com/grepp/spring/app/controller/api/event/payload/response/AllTimeScheduleResponse.java
  src/main/java/com/grepp/spring/app/model/event/dto/AllTimeScheduleDto.java
  src/main/java/com/grepp/spring/app/model/event/service/EventService.java
Labels: ✨ feature, 🔥 매운맛

#127 ♻️ refactor Group의 Command 메서드들에 대한 refactoring 진행
  src/main/java/com/grepp/spring/app/controller/api/group/GroupController.java
  src/main/java/com/grepp/spring/app/model/group/repository/GroupMemberCommandRepository.java
  src/main/java/com/grepp/spring/app/model/group/service/GroupCommandDeleteGroupService.java
  src/main/java/com/grepp/spring/app/model/group/service/GroupCommandExileGroupMemberService.java
  src/main/java/com/grepp/spring/app/model/group/service/GroupCommandGroupTransferService.java
  src/main/java/com/grepp/spring/app/model/group/service/GroupCommandModifyGroupRoleService.java
  src/main/java/com/grepp/spring/app/model/group/service/GroupCommandModifyGroupService.java
  src/main/java/com/grepp/spring/app/model/group/service/GroupCommandService.java
  src/main/java/com/grepp/spring/app/model/group/service/GroupCommandWithdrawService.java
  src/main/java/com/grepp/spring/app/model/schedule/repository/ScheduleCommandRepository.java
  src/main/java/com/grepp/spring/app/model/schedule/repository/ScheduleMemberCommandRepository.java
  src/main/java/com/grepp/spring/app/model/schedule/repository/ScheduleMemberQueryRepository.java
  src/main/java/com/grepp/spring/infra/error/RestApiExceptionAdvice.java
  src/main/java/com/grepp/spring/infra/error/groupAdvice/GroupExceptionAdvice.java
Labels: ♻️ refactor

#147 ✨ feat: 줌 회의장 개설 기능 구현
  src/main/java/com/grepp/spring/app/controller/api/schedules/ScheduleController.java
  src/main/java/com/grepp/spring/app/model/schedule/dto/CreateOnlineMeetingRoomDto.java
  src/main/java/com/grepp/spring/app/model/schedule/dto/ZoomMeetingDto.java
  src/main/java/com/grepp/spring/app/model/schedule/service/ScheduleCommandService.java
  src/main/java/com/grepp/spring/app/model/schedule/service/ZoomOAuthService.java
Labels: ✨ feature

#152 ♻️ refactor: 그룹 전역 예외 처리 refactoring
  src/main/java/com/grepp/spring/app/controller/api/group/GroupController.java
  src/main/java/com/grepp/spring/app/model/group/service/GroupCommandService.java
  src/main/java/com/grepp/spring/app/model/group/service/GroupQueryService.java
  src/main/java/com/grepp/spring/infra/error/exceptions/group/GroupAuthenticationException.java
  src/main/java/com/grepp/spring/infra/error/groupAdvice/GroupExceptionAdvice.java
  src/main/java/com/grepp/spring/infra/response/GroupErrorCode.java
Labels: ♻️ refactor

#160 일정 - 권한관리 로직 추가, 환승정보 '호선', '선' 제거 후 전달, 출발장소 -> 중간장소 결과 재확인, MeetingPlatform 수정, 일정장 에 따른 권한예외, 전역 예외처리
  src/main/java/com/grepp/spring/app/controller/api/external/ExcelUploadController.java
  src/main/java/com/grepp/spring/app/controller/api/schedule/ScheduleController.java
  src/main/java/com/grepp/spring/app/controller/api/schedule/payload/request/CreateDepartLocationRequest.java
  src/main/java/com/grepp/spring/app/controller/api/schedule/payload/request/ModifySchedulesRequest.java
  src/main/java/com/grepp/spring/app/controller/api/schedule/payload/response/ShowScheduleResponse.java
  src/main/java/com/grepp/spring/app/model/schedule/dto/ModifyScheduleDto.java
  src/main/java/com/grepp/spring/app/model/schedule/dto/ScheduleMembersDto.java
  src/main/java/com/grepp/spring/app/model/schedule/dto/ShowScheduleDto.java
  src/main/java/com/grepp/spring/app/model/schedule/repository/ScheduleMemberQueryRepository.java
  src/main/java/com/grepp/spring/app/model/schedule/service/ScheduleCommandService.java
  src/main/java/com/grepp/spring/app/model/schedule/service/ScheduleQueryService.java
  src/main/java/com/grepp/spring/infra/error/exceptions/schedule/LocationNotFoundException.java
  src/main/java/com/grepp/spring/infra/error/exceptions/schedule/NotScheduleMasterException.java
  src/main/java/com/grepp/spring/infra/error/exceptions/schedule/ScheduleMemberNotFoundException.java
  src/main/java/com/grepp/spring/infra/error/exceptions/schedule/WorkSpaceNotFoundException.java
  src/main/java/com/grepp/spring/infra/error/scheduleAdvuce/ScheduleExceptionAdvice.java
  src/main/java/com/grepp/spring/infra/response/ApiResponse.java
  src/main/java/com/grepp/spring/infra/response/ScheduleErrorCode.java
  src/main/resources/lkh.sql
Labels: 🐛bug, 🔧 enhancement

#162 ✨ feat: 로그인 시 클라이언트 지정 uri로 이동하는 기능 구현 완료
  src/main/java/com/grepp/spring/infra/auth/oauth2/CookieAuthorizationRequestRepository.java
  src/main/java/com/grepp/spring/infra/auth/oauth2/CookieUtils.java
  src/main/java/com/grepp/spring/infra/auth/oauth2/OAuth2SuccessHandler.java
  src/main/java/com/grepp/spring/infra/config/security/SecurityConfig.java
Labels: ♻️ refactor, ✨ feature, 🔧 enhancement

#157 ♻️ refactor: 메인페이지 예외처리 + dto 수정
  src/main/java/com/grepp/spring/app/controller/api/group/payload/response/ShowGroupResponse.java
  src/main/java/com/grepp/spring/app/controller/api/mainpage/MainPageController.java
  src/main/java/com/grepp/spring/app/controller/api/mypage/CalendarOAuthController.java
  src/main/java/com/grepp/spring/app/model/group/dto/GroupDetailDto.java
  src/main/java/com/grepp/spring/app/model/group/service/GroupQueryMainpageService.java
  src/main/java/com/grepp/spring/app/model/mainpage/dto/UnifiedScheduleDto.java
  src/main/java/com/grepp/spring/app/model/mainpage/repository/MainPageScheduleRepository.java
  src/main/java/com/grepp/spring/app/model/mainpage/service/CalendarService.java
  src/main/java/com/grepp/spring/app/model/mainpage/service/MainPageService.java
  src/main/java/com/grepp/spring/app/model/mypage/service/GoogleOAuthService.java
  src/main/java/com/grepp/spring/app/model/mypage/service/MypageService.java
  src/main/java/com/grepp/spring/app/model/schedule/repository/ScheduleMemberRepository.java
  src/main/java/com/grepp/spring/infra/error/mypageAdvice/MyPageExceptionAdvice.java
  src/main/resources/jsy.sql
Labels: ♻️ refactor

#166 🔧 chore: 환경 변수 스위칭 기능 추가
  .gitignore
  build.gradle
  src/main/java/com/grepp/spring/app/controller/api/mypage/payload/response/SetCalendarSyncResponse.java
  src/main/java/com/grepp/spring/infra/config/ReactLocalConfig.java
  src/main/java/com/grepp/spring/infra/payload/PageParam.java
Labels: ♻️ refactor, 🔧 enhancement

#170 ♻️ refactor: SecurityContext로부터 가져오는 사용자 정보 호출 관심사 분리
  src/main/java/com/grepp/spring/infra/auth/CurrentUser.java
  src/main/java/com/grepp/spring/infra/auth/CurrentUserArgumentResolver.java
  src/main/java/com/grepp/spring/infra/config/WebConfig.java
Labels: ♻️ refactor, 🔧 enhancement

#172 ♻️ refactor: Event 리팩터링
  src/main/java/com/grepp/spring/app/controller/api/event/EventController.java
  src/main/java/com/grepp/spring/app/controller/api/event/payload/response/AllTimeScheduleResponse.java
  src/main/java/com/grepp/spring/app/controller/api/event/payload/response/CreateEventResponse.java
  src/main/java/com/grepp/spring/app/controller/api/event/payload/response/CreateScheduleResultResponse.java
  src/main/java/com/grepp/spring/app/controller/api/event/payload/response/DeleteEventResponse.java
  src/main/java/com/grepp/spring/app/controller/api/event/payload/response/ScheduleResultResponse.java
  src/main/java/com/grepp/spring/app/controller/api/event/payload/response/ShowEventResponse.java
  src/main/java/com/grepp/spring/app/model/event/dto/AllTimeScheduleDto.java
  src/main/java/com/grepp/spring/app/model/event/dto/CandidateDateDto.java
  src/main/java/com/grepp/spring/app/model/event/dto/CreateEventDto.java
  src/main/java/com/grepp/spring/app/model/event/dto/EventMemberDto.java
  src/main/java/com/grepp/spring/app/model/event/dto/JoinEventDto.java
  src/main/java/com/grepp/spring/app/model/event/dto/ScheduleResultDto.java
  src/main/java/com/grepp/spring/app/model/event/entity/Event.java
  src/main/java/com/grepp/spring/app/model/event/entity/EventMember.java
  src/main/java/com/grepp/spring/app/model/event/factory/EventCreationStrategyFactory.java
  src/main/java/com/grepp/spring/app/model/event/service/EventCommandService.java
  src/main/java/com/grepp/spring/app/model/event/service/EventQueryService.java
  src/main/java/com/grepp/spring/app/model/event/strategy/EventCreationStrategy.java
  src/main/java/com/grepp/spring/app/model/event/strategy/GroupEventCreationStrategy.java
  src/main/java/com/grepp/spring/app/model/event/strategy/SingleEventCreationStrategy.java
Labels: ♻️ refactor

#178 🚨긴급 버그 수정: 일정 - workspace 수정, meetingplatform 수정, 일부 리팩터링
  src/main/java/com/grepp/spring/App.java
  src/main/java/com/grepp/spring/app/controller/api/external/ExcelUploadController.java
  src/main/java/com/grepp/spring/app/controller/api/schedule/ScheduleController.java
  src/main/java/com/grepp/spring/app/controller/api/schedule/payload/request/ModifySchedulesRequest.java
  src/main/java/com/grepp/spring/app/model/schedule/dto/ModifyScheduleDto.java
  src/main/java/com/grepp/spring/app/model/schedule/dto/ModifyWorkspaceDto.java
  src/main/java/com/grepp/spring/app/model/schedule/dto/ScheduleMembersDto.java
  src/main/java/com/grepp/spring/app/model/schedule/dto/ShowScheduleDto.java
  src/main/java/com/grepp/spring/app/model/schedule/service/ExcelUploadService.java
  src/main/java/com/grepp/spring/app/model/schedule/service/ScheduleCommandService.java
  src/main/java/com/grepp/spring/app/model/schedule/service/ScheduleQueryService.java
  src/main/resources/lkh.sql
  src/test/java/com/grepp/spring/app/model/schedule/service/ScheduleQueryServiceTest.java
Labels: ♻️ refactor, 🐛bug, 🔧 enhancement

#180 ♻️ refactor: 인증 및 회원 기능 리팩터링 (+ Swagger 관련 수정)
  src/main/java/com/grepp/spring/app/controller/api/auth/AuthController.java
  src/main/java/com/grepp/spring/app/controller/api/member/MemberController.java
  src/main/java/com/grepp/spring/app/controller/api/member/payload/MemberInfoResponse.java
  src/main/java/com/grepp/spring/app/model/auth/AuthService.java
  src/main/java/com/grepp/spring/app/model/auth/dto/NewTokensDto.java
  src/main/java/com/grepp/spring/app/model/member/entity/Member.java
  src/main/java/com/grepp/spring/app/model/member/service/MemberService.java
  src/main/java/com/grepp/spring/infra/RandomPicker.java
  src/main/java/com/grepp/spring/infra/config/SwaggerConfig.java
Labels: ♻️ refactor

#181 ✨ feat: 참여자 전원 시간대 조회 항목 추가 및 이벤트 조율 결과 생성 검증 강화
  src/main/java/com/grepp/spring/app/controller/api/event/payload/response/AllTimeScheduleResponse.java
  src/main/java/com/grepp/spring/app/model/event/dto/AllTimeScheduleDto.java
  src/main/java/com/grepp/spring/app/model/event/service/EventQueryService.java
  src/main/java/com/grepp/spring/app/model/event/service/EventScheduleResultService.java
  src/main/java/com/grepp/spring/infra/response/EventErrorCode.java
Labels: ✨ feature

#186 ✨ feat: 이벤트 조회 값(미팅 타입) 추가
  src/main/java/com/grepp/spring/app/controller/api/event/payload/response/ShowEventResponse.java
  src/main/java/com/grepp/spring/app/model/event/service/EventQueryService.java
Labels: ✨ feature

#187 ♻️ refactor: 회원 관련 관심사 분리(회원 탈퇴)
  src/main/java/com/grepp/spring/app/model/group/entity/GroupMember.java
  src/main/java/com/grepp/spring/app/model/group/service/GroupCommandService.java
  src/main/java/com/grepp/spring/app/model/member/service/MemberService.java
  src/main/java/com/grepp/spring/app/model/schedule/entity/ScheduleMember.java
  src/main/java/com/grepp/spring/app/model/schedule/service/ScheduleCommandService.java
  src/main/java/com/grepp/spring/infra/error/memberAdvice/AuthExceptionAdvice.java
  src/main/java/com/grepp/spring/infra/error/memberAdvice/MemberExceptionAdvice.java
  src/main/java/com/grepp/spring/infra/utils/RandomPicker.java
Labels: ♻️ refactor

#191 ✨ feat: 메인페이지 일정 활성/비활성 상태 변경 PATCH API 추가
  src/main/java/com/grepp/spring/app/controller/api/mainpage/MainPageController.java
  src/main/java/com/grepp/spring/app/controller/api/mainpage/payload/response/CalendarResponse.java
  src/main/java/com/grepp/spring/app/controller/api/mainpage/payload/response/UpdateActivationResponse.java
  src/main/java/com/grepp/spring/app/model/mainpage/dto/UnifiedScheduleDto.java
  src/main/java/com/grepp/spring/app/model/mainpage/repository/MainPageScheduleMemberRepository.java
  src/main/java/com/grepp/spring/app/model/mainpage/service/MainPageScheduleMemberService.java
  src/main/java/com/grepp/spring/infra/entity/BaseEntity.java
  src/main/java/com/grepp/spring/infra/error/exceptions/mypage/ScheduleMemberIdNotFoundException.java
  src/main/java/com/grepp/spring/infra/error/mypageAdvice/MyPageExceptionAdvice.java
  src/main/java/com/grepp/spring/infra/response/MyPageErrorCode.java
  src/main/resources/jsy.sql
Labels: ✨ feature

#195 ♻️ refactor: 이벤트 리팩터링 및 기능 강화
  src/main/java/com/grepp/spring/app/model/event/entity/EventMember.java
  src/main/java/com/grepp/spring/app/model/event/repository/TempScheduleRepository.java
  src/main/java/com/grepp/spring/app/model/event/service/EventCommandService.java
  src/main/java/com/grepp/spring/app/model/event/service/EventQueryService.java
  src/main/java/com/grepp/spring/app/model/event/service/EventScheduleResultService.java
  src/main/java/com/grepp/spring/app/model/schedule/repository/ScheduleQueryRepository.java
  src/main/java/com/grepp/spring/infra/config/DomainConfig.java
  src/main/java/com/grepp/spring/infra/error/eventAdvice/EventExceptionAdvice.java
  src/main/java/com/grepp/spring/infra/error/exceptions/event/AlreadyConfirmedScheduleException.java
  src/main/java/com/grepp/spring/infra/error/exceptions/event/EventAlreadyCompletedException.java
  src/main/java/com/grepp/spring/infra/response/EventErrorCode.java
  src/test/java/com/grepp/spring/app/model/event/EventCommandServiceTest.java
  src/test/java/com/grepp/spring/app/model/event/EventQueryServiceTest.java
  src/test/java/com/grepp/spring/app/model/event/EventScheduleResultServiceTest.java
Labels: 🔧 enhancement

#196 ✅ test: 회원 탈퇴 로직 테스트 코드 작성
  src/test/java/com/grepp/spring/app/model/member/service/MemberServiceTest.java
Labels: ✅ test

#211 ✅ test: 이벤트 기능 테스트 코드
  src/test/java/com/grepp/spring/app/model/event/EventCommandServiceTest.java
  src/test/java/com/grepp/spring/app/model/event/EventQueryServiceTest.java
  src/test/java/com/grepp/spring/app/model/event/EventScheduleResultService.java
Labels: ✅ test

#219 🐛 fix 확정 이전의 일정에 대한 미조회
  src/main/java/com/grepp/spring/app/model/group/service/GroupQueryService.java
Labels: 🐛bug

#224 ♻️ refactor: FIXED 일정 생성 시 추가 일정 생성의 검증 강화
  src/main/java/com/grepp/spring/app/model/schedule/service/ScheduleCommandService.java
  src/main/java/com/grepp/spring/infra/error/exceptions/schedule/EventNotActivatedException.java
  src/main/java/com/grepp/spring/infra/error/scheduleAdvuce/ScheduleExceptionAdvice.java
  src/main/java/com/grepp/spring/infra/response/ScheduleErrorCode.java
Labels: ♻️ refactor

#221 ♻️ refactor: 비관적 락으로 다수가 동시에 투표하는 상황에서 발생하는 동시성 문제 해결
  src/main/java/com/grepp/spring/app/model/schedule/repository/LocationQueryRepository.java
  src/main/java/com/grepp/spring/app/model/schedule/service/ScheduleCommandService.java
  src/test/java/com/grepp/spring/app/model/schedule/service/ScheduleCommandServiceTest.java
Labels: ♻️ refactor, 🔥 매운맛, 🔧 enhancement

#227 ♻️ refactor: event_members 테이블에 (event_id, member_id) 복합 인덱스 추가
  src/main/resources/indexing_mysql.sql
  src/main/resources/indexing_postgres.sql
Labels: ♻️ refactor, 🔧 enhancement

#222 ✨ feat: 이벤트 all-time 조회 성능 개선을 위한 Redis 캐시 도입
  src/main/java/com/grepp/spring/app/model/event/service/EventCommandService.java
  src/main/java/com/grepp/spring/app/model/event/service/EventQueryService.java
  src/main/java/com/grepp/spring/app/model/event/service/EventScheduleCacheService.java
Labels: 🔧 enhancement

#233 일정 - 일정 조회 에러 수정
  src/main/java/com/grepp/spring/app/controller/api/event/payload/request/CreateEventRequest.java
  src/main/java/com/grepp/spring/app/controller/api/schedule/payload/request/CreateSchedulesRequest.java
  src/main/java/com/grepp/spring/app/model/schedule/dto/ScheduleMembersDto.java
  src/main/java/com/grepp/spring/app/model/schedule/dto/ShowScheduleDto.java
  src/main/java/com/grepp/spring/app/model/schedule/repository/VoteQueryRepository.java
  src/main/java/com/grepp/spring/app/model/schedule/service/ScheduleCommandService.java
  src/main/java/com/grepp/spring/app/model/schedule/service/ScheduleQueryService.java
Labels: 🐛bug

#235 🐛 fix: ScheduleQueryService 메서드에 Transectional Read Only 적용
  src/main/java/com/grepp/spring/app/model/event/entity/Event.java
  src/main/java/com/grepp/spring/app/model/schedule/service/ScheduleQueryService.java
Labels: 🐛bug

#239 ✨ feat: GCP 배포 관련 설정
  .gitignore
  Dockerfile
  docker-compose.yml
  gradlew
  src/main/java/com/grepp/spring/infra/auth/oauth2/OAuth2SuccessHandler.java
  src/main/java/com/grepp/spring/infra/config/SwaggerConfig.java
  src/main/java/com/grepp/spring/infra/config/WebConfig.java
  src/main/resources-env/prod/application.yml
Labels: ✅ done
